// Sections that stay unchanged — not sent to AI
export const PRESERVE_RE = /^(SKILLS?|TECHNICAL SKILLS?|CORE SKILLS?|KEY SKILLS?|TECHNICAL COMPETENCIES|CORE COMPETENCIES|TOOLS?(?: AND TECHNOLOGIES?)?|TECHNOLOGIES?|EDUCATION|ACADEMIC(?: BACKGROUND)?|DEGREES?|CERTIFICATIONS?|LANGUAGES?|AWARDS?)$/i;
